from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import CategoryViewSet, YearViewSet, MSRSeasonYearViewSet, StyleViewSet, ImageViewSet
from django.contrib.auth.views import LogoutView

# Create a router and register our viewsets
router = DefaultRouter()
router.register(r'categories', CategoryViewSet, basename='category')
router.register(r'years', YearViewSet, basename='year')
router.register(r'msr-season-years', MSRSeasonYearViewSet, basename='msr-season-year')
router.register(r'styles', StyleViewSet, basename='style')
router.register(r'images', ImageViewSet, basename='image')

urlpatterns = [
    path('', include(router.urls)),  # Include all routes generated by the router
    path('api-auth/', include('rest_framework.urls')),  # Enables login/logout in DRF UI
    path('logout/', LogoutView.as_view(), name='logout'),  # Add logout URL
]